finished comments
GerFr/starshop pull request #148
Opened 2024-06-09 22:41 UTC by FritzRa

2024-06-09 22:46 UTC, FritzRa commented
#147 
#146 
#145

2024-06-10 07:42 UTC, GerFr requested changes

2024-06-10 07:42 UTC, GerFr commented on index.html
> +                    }
Set to local storage

2024-06-10 07:42 UTC, GerFr commented on index.html
> +                    if (localStorage.getItem("data") !== null) {
Outside of fetch pls

2024-06-10 11:51 UTC, merged